# Generated by Django 2.2 on 2021-11-15 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='age_restricted',
        ),
    ]
